CREATE DATABASE IF NOT EXISTS discord_vote_system CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE discord_vote_system;

CREATE TABLE polls (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  guild_id VARCHAR(32) NOT NULL,
  channel_id VARCHAR(32) NOT NULL,
  question VARCHAR(255) NOT NULL,
  allow_everyone TINYINT(1) NOT NULL DEFAULT 0,
  created_by VARCHAR(64) NULL,
  message_id VARCHAR(32) NULL,
  status ENUM('open','closed') NOT NULL DEFAULT 'open',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  end_at DATETIME NULL,
  INDEX(guild_id), INDEX(channel_id), INDEX(status), INDEX(end_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE poll_options (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  poll_id BIGINT UNSIGNED NOT NULL,
  label VARCHAR(100) NOT NULL,
  emoji VARCHAR(32) NULL,
  vote_count INT UNSIGNED NOT NULL DEFAULT 0,
  FOREIGN KEY (poll_id) REFERENCES polls(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE poll_votes (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  poll_id BIGINT UNSIGNED NOT NULL,
  option_id BIGINT UNSIGNED NOT NULL,
  user_id VARCHAR(32) NOT NULL,
  voted_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (poll_id) REFERENCES polls(id) ON DELETE CASCADE,
  FOREIGN KEY (option_id) REFERENCES poll_options(id) ON DELETE CASCADE,
  UNIQUE KEY uniq_vote (poll_id, user_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
